/**
 * Import Reifier Service — Phase 12.4
 *
 * Scans every TS/TSX/JS/JSX file in a write-batch for relative imports
 * that point to paths not yet on disk or in the current batch.
 * For each "orphan" import it synthesises a minimal stub file and appends
 * it to the batch so the sandbox never boots with broken module resolution.
 *
 * Insertion point: called in aiService.ts immediately before the
 * `for (const file of parsed.filesToWrite)` write loop.
 */

import * as fs from "fs/promises";
import * as path from "path";
import { nexusLog } from "./logService.js";

const log = nexusLog("reifier");

export interface WritableFile {
  path: string;
  content: string;
}

// ---------------------------------------------------------------------------
// Extension resolution order (mirrors Node / Vite defaults)
// ---------------------------------------------------------------------------
const RESOLVE_ORDER = [
  ".ts", ".tsx", ".js", ".jsx",
  "/index.ts", "/index.tsx", "/index.js", "/index.jsx",
];

// Extensions we will attempt to reify (source files only)
const REIFIABLE_EXTS = new Set([".ts", ".tsx", ".js", ".jsx"]);

// ---------------------------------------------------------------------------
// Regex: capture every relative static import / re-export / require
// Groups: [1] named imports clause (may be undefined), [2] module specifier
// ---------------------------------------------------------------------------
const IMPORT_RE =
  /(?:import\s+(?:type\s+)?(?:\*\s+as\s+\w+|\{([^}]*)\}|\w+)\s+from\s+|export\s+(?:type\s+)?\{[^}]*\}\s+from\s+|(?:const|let|var)\s+\S+\s*=\s*require\s*\(\s*)['"](\.[^'"]+)['"]/g;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Return all unique relative specifiers found in a source file. */
function extractRelativeSpecifiers(content: string): { specifier: string; namedImports: string[] }[] {
  const results: Map<string, string[]> = new Map();
  let m: RegExpExecArray | null;
  IMPORT_RE.lastIndex = 0;
  while ((m = IMPORT_RE.exec(content)) !== null) {
    const namedClause = m[1] ?? "";
    const specifier = m[2];
    if (!specifier) continue;
    const named = namedClause
      ? namedClause
          .split(",")
          .map(s => s.replace(/\s+as\s+\w+/, "").trim())
          .filter(Boolean)
      : [];
    if (!results.has(specifier)) results.set(specifier, named);
    else named.forEach(n => results.get(specifier)!.push(n));
  }
  return Array.from(results.entries()).map(([specifier, namedImports]) => ({
    specifier,
    namedImports: [...new Set(namedImports)],
  }));
}

/** Given a file's directory and a specifier, resolve the real file path.
 *  Returns the resolved absolute path or null if nothing matches. */
async function resolveSpecifier(
  fromDir: string,
  specifier: string,
  knownPaths: Set<string>
): Promise<string | null> {
  const base = path.resolve(fromDir, specifier);

  // 1. Exact match (specifier already has an extension)
  if (path.extname(base)) {
    if (knownPaths.has(base)) return base;
    try { await fs.access(base); return base; } catch { /* not found */ }
  }

  // 2. Try resolution order
  for (const ext of RESOLVE_ORDER) {
    const candidate = base + ext;
    if (knownPaths.has(candidate)) return candidate;
    try { await fs.access(candidate); return candidate; } catch { /* try next */ }
  }

  return null; // orphan
}

/** Generate a minimal stub for the given file extension / path. */
function generateStub(stubPath: string, namedImports: string[]): string {
  const ext = path.extname(stubPath).toLowerCase();

  if (ext === ".css" || ext === ".scss" || ext === ".less") {
    return "/* auto-stub generated by Nexus import reifier */\n";
  }

  if (ext === ".json") {
    return "{}\n";
  }

  if (ext === ".svg") {
    return `import React from 'react';\nconst Stub = () => <svg />;\nexport default Stub;\n`;
  }

  // TS/TSX/JS/JSX stub
  const lines: string[] = [
    `// Auto-stub generated by Nexus Import Reifier (Phase 12.4)`,
    `// This file was imported but not yet authored. Replace with real implementation.`,
  ];

  if (namedImports.length > 0) {
    // Export each named symbol as a typed stub so the consumer compiles
    for (const name of namedImports) {
      if (/^[A-Z]/.test(name)) {
        // Looks like a React component or class
        if (ext === ".tsx" || ext === ".jsx") {
          lines.push(`export const ${name} = () => null;`);
        } else {
          lines.push(`export const ${name} = {} as any;`);
        }
      } else {
        lines.push(`export const ${name}: any = undefined;`);
      }
    }
    lines.push(`export default {} as any;`);
  } else {
    lines.push(`export {};`);
  }

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ReifierResult {
  files: WritableFile[];       // original + stubs (stubs appended)
  stubsGenerated: number;
  stubPaths: string[];
}

/**
 * Main entry point.
 *
 * @param filesToWrite  The batch extracted by parseNexusResponse
 * @param sandboxRoot   Absolute path to the session sandbox root
 */
export async function reifyImports(
  filesToWrite: WritableFile[],
  sandboxRoot: string
): Promise<ReifierResult> {
  // Build a normalised set of absolute paths that will be on disk after
  // this batch is written — used to short-circuit disk access.
  const batchAbsPaths = new Set<string>(
    filesToWrite.map(f => path.resolve(sandboxRoot, f.path))
  );

  const stubs: WritableFile[] = [];
  const stubAbsSet = new Set<string>(); // dedup across files

  for (const file of filesToWrite) {
    const ext = path.extname(file.path).toLowerCase();
    if (!REIFIABLE_EXTS.has(ext)) continue; // skip CSS, JSON, etc.

    const fileDir = path.dirname(path.resolve(sandboxRoot, file.path));
    const specifiers = extractRelativeSpecifiers(file.content);

    for (const { specifier, namedImports } of specifiers) {
      // Skip non-relative (node_modules, absolute)
      if (!specifier.startsWith(".")) continue;

      const knownPaths = new Set([...batchAbsPaths, ...stubAbsSet]);
      const resolved = await resolveSpecifier(fileDir, specifier, knownPaths);

      if (resolved) continue; // already known — nothing to stub

      // Determine best stub extension: honour specifier's own ext; otherwise
      // match the importer's ext for TSX/JSX, fall back to .ts.
      const specifierExt = path.extname(specifier); // "" when bare, e.g. "./hooks/useStats"
      const stubExt = specifierExt || ((ext === ".tsx" || ext === ".jsx") ? ext : ".ts");

      // If the specifier already has an extension use it as-is, otherwise append
      const stubAbs = path.resolve(fileDir, specifierExt ? specifier : specifier + stubExt);

      if (stubAbsSet.has(stubAbs) || batchAbsPaths.has(stubAbs)) continue;
      stubAbsSet.add(stubAbs);

      // Relative path within sandbox (for the WritableFile.path field)
      const stubRel = path.relative(sandboxRoot, stubAbs);
      const content = generateStub(stubAbs, namedImports);

      stubs.push({ path: stubRel, content });

      log.info(`[reifier] Stub generated: ${stubRel} (for import "${specifier}" in ${file.path})`);
    }
  }

  // Merge: original files first, then stubs (stubs never overwrite authored files)
  const merged = [...filesToWrite, ...stubs];

  if (stubs.length > 0) {
    log.info(`[reifier] ✔ ${stubs.length} stub(s) appended to write batch`);
  } else {
    log.info(`[reifier] ✔ All imports resolved — no stubs needed`);
  }

  return {
    files: merged,
    stubsGenerated: stubs.length,
    stubPaths: stubs.map(s => s.path),
  };
}
